language: r

cache: packages

sudo: required

r_packages:
  - covr

apt_packages:
  - r-cran-rjava

before_install:
  - sudo $(which R) CMD javareconf

after_success:
  -  Rscript -e 'library(covr); codecov()'

notifications:
  email:
    recipients:
      - miguel.ferreiro.diaz@gmail.com
    on_success: change
    on_failure: always
